require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/User');
const Car = require('../models/Car');
const Booking = require('../models/Booking');

const MONGODB_URI = process.env.MONGODB_URI;

const adminUser = {
  name: 'DriveEase Admin',
  email: process.env.ADMIN_EMAIL || 'admin@driveease.in',
  password: process.env.ADMIN_PASSWORD || 'Admin@123456',
  phoneNumber: '9876543210',
  role: 'admin',
};

const cars = [
  // ─── HATCHBACKS ───
  {
    name: 'Swift',
    brand: 'Maruti Suzuki',
    category: 'Hatchback',
    city: 'Delhi',
    pricePerDay: 1200,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: 5,
    rating: 4.3,
    totalRatings: 234,
    mileage: '22 km/l',
    year: 2024,
    description: 'India\'s favourite hatchback. The new Swift delivers sporty looks, peppy performance and excellent fuel efficiency. Perfect for city drives.',
    features: ['ABS', 'Dual Airbags', 'Touchscreen Infotainment', 'Rear Parking Camera', 'Keyless Entry'],
    images: [{ url: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'i20',
    brand: 'Hyundai',
    category: 'Hatchback',
    city: 'Mumbai',
    pricePerDay: 1400,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.4,
    totalRatings: 189,
    mileage: '20 km/l',
    year: 2024,
    description: 'Premium hatchback with bold design and segment-first features. Loaded with tech and comfort for modern urban driving.',
    features: ['6 Airbags', 'Sunroof', 'Wireless Charging', 'Connected Car Tech', 'Ventilated Seats'],
    images: [{ url: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Altroz',
    brand: 'Tata',
    category: 'Hatchback',
    city: 'Bengaluru',
    pricePerDay: 1100,
    fuelType: 'Diesel',
    transmission: 'Manual',
    seats: 5,
    rating: 4.2,
    totalRatings: 156,
    mileage: '25 km/l',
    year: 2024,
    description: 'Gold standard of safety with a 5-star GNCAP rating. The Altroz combines bold IMPACT 2.0 design with outstanding diesel efficiency.',
    features: ['5-Star Safety', 'ABS with EBD', 'Harman Audio', '7-inch Touchscreen', 'iRA Connected Car'],
    images: [{ url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Baleno',
    brand: 'Maruti Suzuki',
    category: 'Hatchback',
    city: 'Pune',
    pricePerDay: 1300,
    fuelType: 'CNG',
    transmission: 'Manual',
    seats: 5,
    rating: 4.1,
    totalRatings: 198,
    mileage: '30 km/kg',
    year: 2024,
    description: 'Premium hatchback now available in CNG. Gives exceptional fuel economy with factory-fitted CNG kit for budget-conscious drivers.',
    features: ['Factory CNG', 'SmartPlay Pro+', 'Heads Up Display', '360 View Camera', 'LED DRLs'],
    images: [{ url: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },

  // ─── SEDANS ───
  {
    name: 'City',
    brand: 'Honda',
    category: 'Sedan',
    city: 'Chennai',
    pricePerDay: 1800,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.5,
    totalRatings: 312,
    mileage: '18 km/l',
    year: 2024,
    description: 'The legendary sedan that defines sophistication. Honda City delivers a sublime driving experience with refined engine and premium interiors.',
    features: ['CVT Transmission', 'Lane Watch Camera', 'Honda Connect', 'LED Headlamps', '6 Airbags'],
    images: [{ url: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Verna',
    brand: 'Hyundai',
    category: 'Sedan',
    city: 'Hyderabad',
    pricePerDay: 1900,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.4,
    totalRatings: 267,
    mileage: '19 km/l',
    year: 2024,
    description: 'All-new Verna with stunning design language, advanced ADAS features, and a turbo petrol engine. A true driver\'s sedan.',
    features: ['ADAS Level 2', 'Ventilated Seats', 'Dual Zone Climate', 'BOSE Audio', 'Wireless CarPlay'],
    images: [{ url: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Slavia',
    brand: 'Skoda',
    category: 'Sedan',
    city: 'Delhi',
    pricePerDay: 1700,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: 5,
    rating: 4.2,
    totalRatings: 143,
    mileage: '20 km/l',
    year: 2024,
    description: 'The drivers\' sedan with European engineering. Offers the best-in-class driving dynamics and a spacious cabin for long road trips.',
    features: ['TSI Engine', 'Ventilated Seats', '10-inch Touchscreen', '6 Airbags', 'Cruise Control'],
    images: [{ url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Camry',
    brand: 'Toyota',
    category: 'Sedan',
    city: 'Mumbai',
    pricePerDay: 4500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.7,
    totalRatings: 89,
    mileage: '19 km/l',
    year: 2024,
    description: 'Toyota\'s flagship sedan. Hybrid powertrain delivers exceptional refinement with premium luxury cabin. Perfect for executive travel.',
    features: ['Hybrid Engine', 'JBL Audio', 'HUD', 'Rear Sunshade', '9 Airbags', 'Leather Seats'],
    images: [{ url: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },

  // ─── SUVs ───
  {
    name: 'Creta',
    brand: 'Hyundai',
    category: 'SUV',
    city: 'Bengaluru',
    pricePerDay: 2200,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.5,
    totalRatings: 456,
    mileage: '21 km/l',
    year: 2024,
    description: 'India\'s most loved SUV. The Creta offers bold design, feature-loaded interiors, and dependable performance across all terrains.',
    features: ['Panoramic Sunroof', 'ADAS', 'Ventilated Seats', 'BOSE Audio', '360 Camera', 'Connected Car Tech'],
    images: [{ url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Nexon',
    brand: 'Tata',
    category: 'SUV',
    city: 'Jaipur',
    pricePerDay: 1600,
    fuelType: 'Petrol',
    transmission: 'Manual',
    seats: 5,
    rating: 4.3,
    totalRatings: 378,
    mileage: '17 km/l',
    year: 2024,
    description: 'India\'s safest SUV with 5-star GNCAP rating. Compact, stylish and loaded with smart features for the modern Indian family.',
    features: ['5-Star Safety', 'Electric Sunroof', 'iRA Connected Car', 'Rain Sensing Wipers', 'Auto Headlamps'],
    images: [{ url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Seltos',
    brand: 'Kia',
    category: 'SUV',
    city: 'Chandigarh',
    pricePerDay: 2000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.4,
    totalRatings: 289,
    mileage: '20 km/l',
    year: 2024,
    description: 'Tech-loaded SUV with bold tiger-nose design. Features ADAS, connected car tech, and powerful performance for highway cruising.',
    features: ['ADAS', 'BOSE Audio', 'Air Purifier', '10.25-inch Screen', 'Ventilated Seats', 'Drive Modes'],
    images: [{ url: 'https://images.unsplash.com/photo-1568844293986-8d0400f4745b?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Scorpio N',
    brand: 'Mahindra',
    category: 'SUV',
    city: 'Delhi',
    pricePerDay: 2400,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    rating: 4.3,
    totalRatings: 234,
    mileage: '16 km/l',
    year: 2024,
    description: 'The Big Daddy of SUVs. New Scorpio-N is a proper body-on-frame SUV with powerful diesel, 4WD, and muscular road presence.',
    features: ['4WD', 'AdrenoX Connected', 'Sony 3D Audio', 'Dual Zone AC', '6 Airbags', 'Terrain Modes'],
    images: [{ url: 'https://images.unsplash.com/photo-1606611013016-969c19ba27a5?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'XUV700',
    brand: 'Mahindra',
    category: 'SUV',
    city: 'Kolkata',
    pricePerDay: 2800,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    rating: 4.6,
    totalRatings: 312,
    mileage: '16 km/l',
    year: 2024,
    description: 'Sophisticated technology meets raw power. XUV700 features the most advanced ADAS suite in India with stunning performance.',
    features: ['ADAS', 'Panoramic Sunroof', 'Alexa Built-in', 'Sony 3D Audio', 'Flush Door Handles', '7 Airbags'],
    images: [{ url: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Harrier',
    brand: 'Tata',
    category: 'SUV',
    city: 'Mumbai',
    pricePerDay: 2500,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.4,
    totalRatings: 198,
    mileage: '17 km/l',
    year: 2024,
    description: 'Built on the legendary OMEGARC platform. The Harrier commands attention with its imposing design and premium driving experience.',
    features: ['Panoramic Sunroof', 'JBL Audio', 'ADAS', 'Ventilated Seats', '360 Camera', 'Air Purifier'],
    images: [{ url: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Fortuner',
    brand: 'Toyota',
    category: 'SUV',
    city: 'Hyderabad',
    pricePerDay: 3500,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    rating: 4.6,
    totalRatings: 267,
    mileage: '14 km/l',
    year: 2024,
    description: 'The undisputed king of full-size SUVs in India. Toyota Fortuner delivers legendary reliability, 4WD capability and commanding road presence.',
    features: ['4WD', 'Paddle Shifters', 'Connected Car Tech', 'Cooled Seats', '7 Airbags', 'Differential Lock'],
    images: [{ url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },

  // ─── LUXURY ───
  {
    name: '3 Series',
    brand: 'BMW',
    category: 'Luxury',
    city: 'Mumbai',
    pricePerDay: 6500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.8,
    totalRatings: 67,
    mileage: '15 km/l',
    year: 2024,
    description: 'The ultimate driving machine. BMW 3 Series offers an exhilarating blend of sporty dynamics, luxury interiors and cutting-edge technology.',
    features: ['BMW Live Cockpit', 'Harman Kardon Audio', 'Gesture Control', 'Ambient Lighting', 'M Sport Package'],
    images: [{ url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'C-Class',
    brand: 'Mercedes-Benz',
    category: 'Luxury',
    city: 'Bengaluru',
    pricePerDay: 7500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.9,
    totalRatings: 45,
    mileage: '14 km/l',
    year: 2024,
    description: 'The epitome of luxury sedans. The all-new C-Class brings S-Class technology into a sporty package with the MBUX hyperscreen.',
    features: ['MBUX System', 'Burmester 3D Audio', 'Digital Key', 'ADAS', 'Ambient Lighting', 'Memory Seats'],
    images: [{ url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'A4',
    brand: 'Audi',
    category: 'Luxury',
    city: 'Delhi',
    pricePerDay: 7000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.7,
    totalRatings: 56,
    mileage: '15 km/l',
    year: 2024,
    description: 'Audi\'s best-selling sedan. The A4 combines Vorsprung durch Technik with a refined 2.0 TFSI engine and Quattro-inspired design.',
    features: ['Virtual Cockpit', 'Matrix LED', 'MMI Navigation', 'Bang & Olufsen Audio', '8 Airbags', 'Drive Select'],
    images: [{ url: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },

  // ─── ELECTRIC ───
  {
    name: 'Nexon EV',
    brand: 'Tata',
    category: 'Electric',
    city: 'Bengaluru',
    pricePerDay: 2000,
    fuelType: 'Electric',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.4,
    totalRatings: 178,
    mileage: '312 km range',
    year: 2024,
    description: 'India\'s best-selling electric SUV. The Nexon EV MAX offers 312km range, fast charging, and zippy performance with zero emissions.',
    features: ['312km Range', 'Fast Charging', 'Connected Car', 'ZConnect App', 'Regenerative Braking', 'Drive Modes'],
    images: [{ url: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'XUV400',
    brand: 'Mahindra',
    category: 'Electric',
    city: 'Pune',
    pricePerDay: 2200,
    fuelType: 'Electric',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.3,
    totalRatings: 89,
    mileage: '456 km range',
    year: 2024,
    description: 'Mahindra\'s born-electric SUV with an impressive 456km range. Sporty design, fast charging and exhilarating performance.',
    features: ['456km Range', 'Fast Charging', 'AdrenoX', 'Sunroof', '6 Airbags', 'Smart Door Handles'],
    images: [{ url: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'EV6',
    brand: 'Kia',
    category: 'Electric',
    city: 'Delhi',
    pricePerDay: 5000,
    fuelType: 'Electric',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.7,
    totalRatings: 34,
    mileage: '528 km range',
    year: 2024,
    description: 'Award-winning electric crossover with stunning design. Ultra-fast 800V charging, 528km range and thrilling 0-100 in 5.2 seconds.',
    features: ['800V Fast Charging', 'Vehicle-to-Load', 'Augmented Reality HUD', 'Meridian Audio', 'Remote Smart Parking'],
    images: [{ url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },

  // ─── MORE CITY COVERAGE ───
  {
    name: 'Grand Vitara',
    brand: 'Maruti Suzuki',
    category: 'SUV',
    city: 'Chennai',
    pricePerDay: 2100,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.3,
    totalRatings: 167,
    mileage: '27 km/l',
    year: 2024,
    description: 'Strong hybrid SUV with best-in-class fuel economy. Grand Vitara combines Toyota hybrid tech with Suzuki style.',
    features: ['Strong Hybrid', 'Panoramic Sunroof', 'Head Up Display', '360 Camera', 'Wireless Charging'],
    images: [{ url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Hector',
    brand: 'MG',
    category: 'SUV',
    city: 'Jaipur',
    pricePerDay: 2300,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.2,
    totalRatings: 156,
    mileage: '14 km/l',
    year: 2024,
    description: 'India\'s Internet car. MG Hector brings a massive 14-inch touchscreen, i-Smart connected tech and spacious interiors.',
    features: ['14-inch Touchscreen', 'i-Smart 2.0', 'Panoramic Sunroof', 'Infinity Roof', '6 Airbags', 'ADAS'],
    images: [{ url: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Innova Hycross',
    brand: 'Toyota',
    category: 'SUV',
    city: 'Kolkata',
    pricePerDay: 3000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 7,
    rating: 4.5,
    totalRatings: 198,
    mileage: '21 km/l',
    year: 2024,
    description: 'The most trusted name in people-movers, now with strong hybrid. Ottoman seats, hybrid efficiency and Toyota reliability.',
    features: ['Strong Hybrid', 'Ottoman Seats', 'Panoramic Sunroof', 'JBL Audio', '360 Camera', 'Connected Tech'],
    images: [{ url: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0afe?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
  {
    name: 'Dzire',
    brand: 'Maruti Suzuki',
    category: 'Sedan',
    city: 'Chandigarh',
    pricePerDay: 1100,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    rating: 4.1,
    totalRatings: 445,
    mileage: '24 km/l',
    year: 2024,
    description: 'India\'s most popular compact sedan. Dzire offers spacious interiors, excellent mileage and AMT convenience for daily commutes.',
    features: ['AMT Gearbox', 'SmartPlay Studio', 'Auto Fold Mirrors', 'LED DRLs', 'Dual Airbags'],
    images: [{ url: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80', publicId: '' }],
    isAvailable: true,
  },
];

const seedDatabase = async () => {
  try {
    console.log('🔗 Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB\n');

    // Clear existing data
    console.log('🧹 Clearing existing data...');
    await Promise.all([
      User.deleteMany({}),
      Car.deleteMany({}),
      Booking.deleteMany({}),
    ]);
    console.log('✅ Existing data cleared\n');

    // Create admin user
    console.log('👤 Creating admin user...');
    const admin = await User.create(adminUser);
    console.log(`✅ Admin created: ${admin.email}\n`);

    // Create demo user
    console.log('👤 Creating demo user...');
    const demoUser = await User.create({
      name: 'Rahul Sharma',
      email: 'rahul@example.com',
      password: 'User@123456',
      phoneNumber: '9876543211',
      role: 'user',
    });
    console.log(`✅ Demo user created: ${demoUser.email}\n`);

    // Seed cars
    console.log('🚗 Seeding cars...');
    const createdCars = await Car.insertMany(cars);
    console.log(`✅ ${createdCars.length} cars seeded successfully\n`);

    // Summary
    console.log('═══════════════════════════════════════');
    console.log('  🎉 DATABASE SEEDED SUCCESSFULLY!');
    console.log('═══════════════════════════════════════');
    console.log(`  Admin Email:    ${adminUser.email}`);
    console.log(`  Admin Password: ${adminUser.password}`);
    console.log(`  Demo Email:     rahul@example.com`);
    console.log(`  Demo Password:  User@123456`);
    console.log(`  Total Cars:     ${createdCars.length}`);
    console.log('═══════════════════════════════════════\n');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error.message);
    process.exit(1);
  }
};

seedDatabase();
